# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: iOS SPM Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

    # Build the Swift package for iOS simulator
    - name: Build for iOS Simulator
      run: xcodebuild -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \-scheme NetworkLayer-Package\-sdk iphonesimulator build

    # Run tests on iOS simulator
    - name: Run tests on iOS Simulator
      run: xcodebuild -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \-scheme NetworkLayer-Package\-sdk iphonesimulator test

