name: iOS SPM Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest
    env:
      SCHEME: NetworkLayer
      DESTINATION: "platform=iOS Simulator,name=iPhone 16,OS=18.1"
      DERIVED_DATA: ${{ github.workspace }}/DerivedData

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: Print Xcode version
        run: |
          xcodebuild -version
          xcode-select -p

      # Instalar SwiftLint desde Homebrew
      - name: Install SwiftLint via Homebrew
        shell: bash
        run: |
          set -euo pipefail
          brew update
          brew install swiftlint
          swiftlint version

      # Lint estricto
      - name: SwiftLint (lint --strict)
        shell: bash
        run: swiftlint lint --strict

      - name: Run tests on iOS Simulator
        shell: bash
        run: |
          set -euo pipefail
          xcodebuild \
            -destination "$DESTINATION" \
            -scheme "$SCHEME" \
            -sdk iphonesimulator \
            -derivedDataPath "$DERIVED_DATA" \
            test
