name: iOS SPM Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest
    env:
      SCHEME: NetworkLayer
      DESTINATION: "platform=iOS Simulator,name=iPhone 14,OS=latest"
      DERIVED_DATA: ${{ github.workspace }}/DerivedData

    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      # Instalar SwiftLint desde Homebrew
      - name: Install SwiftLint via Homebrew
        shell: bash
        run: |
          set -euo pipefail
          brew update
          brew install swiftlint
          swiftlint version

      # Lint estricto
      - name: SwiftLint (lint --strict)
        shell: bash
        run: swiftlint lint --strict

      - name: Run tests on iOS Simulator
        shell: bash
        run: |
          set -euo pipefail
          xcodebuild \
            -destination "$DESTINATION" \
            -scheme "$SCHEME" \
            -sdk iphonesimulator \
            -derivedDataPath "$DERIVED_DATA" \
            test
